export const featureGroups = [
  { id: 'capture', eyebrow: '01 · Capture', title: 'Collect an authorized source', image: '/features/cross-site-handoff.png', copy: 'Enable Inspect Mode for hover controls, use the UploadFlow context menu, or paste a direct media URL. UploadFlow stores a bounded source reference rather than silently downloading every file.', points: ['Images, video, audio, and media links', 'Optional hover inspection and right-click capture', 'Signed and protected URLs remain subject to source access rules'] },
  { id: 'shelf', eyebrow: '02 · Organize', title: 'Keep media available across tabs', image: '/features/media-shelf-actual.png', copy: 'The persistent side panel uses the same local shelf as the picker and editor. Search, tag, favourite, collect, select, and track work while moving from source to destination websites.', points: ['Bounded local shelf of source references', 'Collections, tags, favourites, and multi-select', 'Queue progress, retry, cancellation, and completed-item removal'], comingSoon: true },
  { id: 'prepare', eyebrow: '03 · Prepare', title: 'Choose the depth the task needs', image: '/features/workspace-settings-actual.png', imageLabel: 'Actual extension workspace · Settings shown', copy: 'Use quick actions in the popup, manage several items in the side panel, or open the full workspace. Settings control interception, pickers, editor defaults, presets, brand kits, packs, and optional history.', points: ['Optimize and convert images', 'Crop, redact, watermark, upscale, or prepare supported video', 'Destination presets, filename templates, and reusable brand kits'], comingSoon: true },
  { id: 'optimize', eyebrow: '04 · Optimize', title: 'Make images upload-ready', image: '/features/optimize-actual.png', imageLabel: 'Actual extension workspace · Optimize', copy: 'Resize, compress, convert, rename, and remove supported metadata while comparing the current output against the original.', points: ['JPEG, PNG, and WebP output choices', 'Independent dimension and quality controls', 'Local metadata scan and clean export'] },
  { id: 'crop', eyebrow: '05 · Compose', title: 'Crop for the destination', image: '/features/crop-actual.png', imageLabel: 'Actual extension workspace · Crop', copy: 'Prepare square, portrait, landscape, and thumbnail compositions. Focus controls and preview zoom keep framing deliberate before the crop is applied.', points: ['Reusable destination aspect ratios', 'Adjustable horizontal and vertical focus', 'Preview before replacing the current draft'], comingSoon: true },
  { id: 'redact', eyebrow: '06 · Protect', title: 'Redact private regions', image: '/features/redact-actual.png', imageLabel: 'Actual extension workspace · Redact', copy: 'Draw blur or cover regions on the original, preview the cleaned result, and apply only after reviewing the before-and-after workspace.', points: ['Manual privacy regions', 'Undo, redo, and clear-region controls', 'Temporary preview before applying the output'] },
  { id: 'watermark', eyebrow: '07 · Brand', title: 'Apply a reusable watermark', image: '/features/watermark-actual.png', imageLabel: 'Actual extension workspace · Watermark', copy: 'Use custom text or a saved brand-kit variant, then control placement, font, colour, alignment, and baseline against a live preview.', points: ['Text and brand-kit variants', 'Nine-point positioning', 'Reusable visual identity across outputs'] },
  { id: 'upscale', eyebrow: '08 · Resolve', title: 'Upscale when resolution is missing', image: '/features/upscale-actual.png', imageLabel: 'Actual extension workspace · Upscale', copy: 'Choose a supported enlargement factor, inspect the estimated output dimensions, and compare the generated result with the original.', points: ['2x and supported 4x resolution modes', 'Before-and-after review', 'Explicit network action to the configured processor'] },
  { id: 'batch', eyebrow: '09 · Scale', title: 'Build batches and platform variants', image: '/features/batch-packs-actual.png', imageLabel: 'Actual side panel · Batch and platform-pack controls shown', copy: 'Selected compatible items can enter a bounded queue. Platform packs generate purposeful variants with deterministic names and can be downloaded together as a locally assembled ZIP.', points: ['Bounded URL and CPU-heavy work concurrency', 'Per-item progress, retry, cancellation, and errors', 'Square, portrait, landscape, thumbnail, preview, and high-quality variants'], comingSoon: true },
  { id: 'video', eyebrow: '10 · Video', title: 'Trim and prepare video locally', image: '/features/editor-workspace.png', imageLabel: 'Concept preview · Coming soon', concept: true, copy: 'The video workspace is being moved to a packaged FFmpeg Wasm pipeline for deterministic trimming, crop, resize, speed, audio, cover-frame, and broadly playable MP4 output.', points: ['Locally bundled worker and Wasm assets', 'Frame-accurate processing without real-time playback capture', 'Cancellable jobs with explicit progress'], comingSoon: true },
  { id: 'handoff', eyebrow: '11 · Handoff', title: 'Return the approved File', image: '/features/cross-site-handoff.png', copy: 'When a destination asks for a file, UploadFlow retrieves the selected source on demand, opens review, and returns the approved File to the original input, drop, paste, or supported page API flow.', points: ['Continue returns the prepared File', 'Cancel discards the temporary result', 'Explicit Download hands progress and saving to Chrome'] },
  { id: 'downloads', eyebrow: '12 · Download', title: 'Let Chrome own long-running saves', image: '/features/downloads-actual.png', imageLabel: 'Actual extension workspace · Downloads', copy: 'Explicit downloads continue through Chrome after the UploadFlow window closes. The activity view keeps their progress and completed state visible.', points: ['Browser-managed progress', 'Completed download history and Show file', 'Clear completed items without deleting saved files'] },
  { id: 'history', eyebrow: '13 · Repeat', title: 'Optionally remember the workflow', copy: 'Private history is disabled by default. When enabled, it stores bounded workflow metadata—not file bytes—with 7, 30, or 90-day retention and clear-all or per-destination deletion.', points: ['Local perceptual duplicate warnings', 'Repeat a previous editor workflow', 'No persisted fingerprints, scan findings, video frames, or temporary output bytes'], comingSoon: true }
];
